space_size         = 1


sampler_parameters = {"Space size"                    : space_size                                                                    ,
                      "Power sinus 1D"                : {"Power" : 1}                                                                 ,
                      "Heaviside 1D"                  : {"x gaps" : [0, 0.5, 1], "steps value" : [1, -1], "sigma noises" : [0.2, 0.2]},
                      "Multimodal sinus 1D"           : {"x gaps" : [0, 0.5, 1], "speeds value" : [1, 2]}                             ,
                      "Noisy sinus 1D"                : {"sigma noise" : 0.2}                                                         ,
                      "Sinus times x 1D"              : {}                                                                            ,
                      "Sinus cardinal 1D"             : {}                                                                            ,
                      "Slide function"                : {}                                                                            ,
                      "Two bumps"                     : {}                                                                            ,
                      "Power sinus 2D"                : {"Power" : 1}                                                                 ,
                      "Heaviside 2D"                  : {"x gaps" : [0, 1, 2], "steps value" : [1, -1], "sigma noises" : [0.2, 0.2]}  ,
                      "Multimodal sinus 2D"           : {"x gaps" : [0, 1, 2], "speeds value" : [1, 2]}                               ,
                      "Noisy sinus 2D"                : {"sigma noise" : 0.2}                                                         ,
                      "Sinus times x 2D"              : {}                                                                            ,
                      "Sinus cardinal 2D"             : {}                                                                            ,
                      "Gaussian process trajectory"   : {"sigma0" : 1, "theta" : 1}                                                   ,
                      "Concrete compressive strength" : {}                                                                            ,
                      "Energy efficiency"             : {}                                                                            ,
                      "Auto mpg"                      : {}                                                                            ,
                      "Combined cycle power plant"    : {}                                                                            ,
                      "Airfoil self-noise"            : {}                                                                            ,
                      "Morokoff & caflisch 1"         : {"Dimension" : 2}                                                             ,
                      "Morokoff & caflisch 2"         : {"Dimension" : 2}                                                             ,
                      "Branin"                        : {}                                                                            ,
                      "Branin hoo"                    : {}                                                                            ,
                      "Goldstein"                     : {}                                                                            ,
                      "Goldstein price"               : {}                                                                            ,
                      "Rosenbrock4"                   : {}                                                                            ,
                      "Hartman4"                      : {}                                                                            ,
                      "Hartman6"                      : {}                                                                            ,
                      "Sphere6"                       : {}                                                                            ,
                      "Iooss1"                        : {}                                                                            ,
                      "Iooss2"                        : {}                                                                            ,
                      "Wing weight"                   : {}                                                                            ,
                      "Sobol"                         : {"a" : [1, 10]}                                                               ,
                      "Two input toy"                 : {}                                                                            ,
                      "Highly non linear"             : {}                                                                            ,
                      "Mystery"                       : {}                                                                            ,
                      "Six hump camelback"            : {}                                                                            ,
                      "Ishigami"                      : {}}
